"use client"

import { Card, CardContent } from "@/components/ui/card"
import { Icon3D } from "./3d-icons"
import { cn } from "@/lib/utils"

interface KPICardProps {
  title: string
  value: string
  trend: string
  trendPositive?: boolean
  iconType: "dollar" | "users" | "sparkles"
}

function KPICard({ title, value, trend, trendPositive = true, iconType }: KPICardProps) {
  return (
    <Card className="bg-card border-border/50">
      <CardContent className="p-6">
        <div className="flex items-start justify-between">
          <div className="space-y-3">
            <p className="text-sm text-muted-foreground">{title}</p>
            <p className="text-3xl font-semibold tracking-tight text-foreground">{value}</p>
            <p className={cn(
              "text-sm",
              trendPositive ? "text-emerald-400" : "text-muted-foreground"
            )}>
              {trend}
            </p>
          </div>
          <Icon3D type={iconType} size={56} />
        </div>
      </CardContent>
    </Card>
  )
}

export function KPICards() {
  const kpis: Array<{
    title: string
    value: string
    trend: string
    trendPositive: boolean
    iconType: "dollar" | "users" | "sparkles"
  }> = [
    {
      title: "Total Revenue",
      value: "RM 45,200",
      trend: "+12% vs last month",
      trendPositive: true,
      iconType: "dollar",
    },
    {
      title: "Active Members",
      value: "3,405",
      trend: "+58 this week",
      trendPositive: true,
      iconType: "users",
    },
    {
      title: "AI ROI",
      value: "RM 8,500",
      trend: "Generated by Auto-Promos",
      trendPositive: true,
      iconType: "sparkles",
    },
  ]

  return (
    <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
      {kpis.map((kpi) => (
        <KPICard key={kpi.title} {...kpi} />
      ))}
    </div>
  )
}
